-- Loosen the default RFID tracking floor from -5000 (-50 dBm) to -6500 (-65 dBm).
-- Mirrors backend/src/db/migrations/0032_rssi_threshold_default.sql — the events
-- table lives in both the local Fastify Postgres and Supabase, so both need it.
--
-- Measured at the 2026-08-07 night race: every genuine finish crossing came in at
-- -60…-65 dBm; the strongest read of the whole race was -45.5 dBm. A -5000 default
-- discards essentially the whole field. Far-field pickup sits at -71…-78 dBm, so
-- -6500 still excludes it.
--
-- Existing rows are untouched: rssi_threshold is a per-event operational setting and
-- past events must keep the value their results were produced with.
ALTER TABLE public.events ALTER COLUMN rssi_threshold SET DEFAULT -6500;
